DROP TABLE IF EXISTS COURSES;
DROP TABLE IF EXISTS TEACHERS;

CREATE TABLE TEACHERS (
  teacherId INT PRIMARY KEY AUTO_INCREMENT,
  teacherName VARCHAR NOT NULL
);
  

CREATE TABLE COURSES (
  courseId      INT PRIMARY KEY AUTO_INCREMENT,
  title   		VARCHAR NOT NULL,
  level			VARCHAR NOT NULL DEFAULT 'Principiante' CHECK level in ('Principiante', 'Intermedio', 'Avanzado'),
  hours		   	INT DEFAULT 10,
  teacherId		INT NOT NULL,
  active		BOOLEAN DEFAULT FALSE
);


ALTER TABLE COURSES 
ADD FOREIGN KEY (teacherId) 
REFERENCES TEACHERS(teacherId);